a=input('Introduceti primul nume :')
b=input('Introduceti al doilea nume :')
print( "Lungimea primului nime este :" ,len(a))
print("Cele doua nume date sunt la fel" ,a==b)
print('Primul nume e mai lung decat al doilea ' , len(a)>len(b))
print("Initiala primului nume este :" , a[0])
print("Primul nume inversat este :" , a[::-1])