a=input("Introduceti un nume de referinta:")
b=input("Introduceti alt nume")
print("Lungimea numelui de referinta este :",len(a))
print("Numele de referinta este acelasi",a==b)
print("Numele de referintaeste este mmai lung", len(a)>len(b))
print("Initiala numelui de referinta este",a[0])
print("Numele de referinta inversat este",a[::-1])
c=int(input("Introduceti un numar:"))
print(a*c)